name: chromRL
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - pip
  - wheel        
  - xz          
  - zlib      

  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - ansicon==1.89.0
      - blessed==1.20.0
      - docker-pycreds==0.4.0
      - farama-notifications==0.0.4
      - gpustat==1.1.1
      - grpcio==1.70.0
      - gymnasium==1.0.0
      - idna==3.10
      - jinja2==3.1.5
      - jinxed==1.3.0
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - markdown==3.7
      - markupsafe==3.0.2
      - networkx==3.4.2
      - nvidia-ml-py==12.570.86
      - packaging==24.2
      - pillow==11.1.0
      - platformdirs==4.3.6
      - protobuf==5.29.3
      - psutil==6.1.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - sb3-contrib==2.5.0
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - stable-baselines3==2.5.0
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - wandb==0.19.4
      - wcwidth==0.2.13
      - werkzeug==3.1.3
